name: Build Flutter APK

on:
  push:
    branches:
      - main  # or master depending on your branch name
  workflow_dispatch: # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: triptrap-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk


  name: Set up Flutter
  uses: subosito/flutter-action@v2
  with:
    channel: stable
    flutter-version: '3.22.1' 
